complete -c dolt -f
complete -c dolt -n __fish_use_subcommand -a init -d "Create an empty Dolt data repository."
complete -c dolt -n "__fish_seen_subcommand_from init" -s b -l initial-branch -d "The branch name used to initialize this database. If not provided will be taken from init.defaultbranch in the global config. If unset, the default initialized branch will be named 'main'."
complete -c dolt -n "__fish_seen_subcommand_from init" -l name -d "The name used in commits to this repo. If not provided will be taken from user.name in the global config."
complete -c dolt -n "__fish_seen_subcommand_from init" -l email -d "The email address used. If not provided will be taken from user.email in the global config."
complete -c dolt -n "__fish_seen_subcommand_from init" -l date -d "Specify the date used in the initial commit. If not specified the current system time is used."
complete -c dolt -n "__fish_seen_subcommand_from init" -l fun -d "No description"
complete -c dolt -n __fish_use_subcommand -a status -d "Show the working tree status."
complete -c dolt -n "__fish_seen_subcommand_from status" -l ignored -d "Show tables that are ignored (according to dolt_ignore)"
complete -c dolt -n __fish_use_subcommand -a add -d "Add table changes to the list of staged table changes."
complete -c dolt -n "__fish_seen_subcommand_from add" -s A -l all -d "Stages any and all changes (adds, deletes, and modifications) except for ignored tables."
complete -c dolt -n "__fish_seen_subcommand_from add" -s f -l force -d "Allow adding otherwise ignored tables."
complete -c dolt -n __fish_use_subcommand -a diff -d "Diff a table."
complete -c dolt -n "__fish_seen_subcommand_from diff" -s sk -l skinny -d "Shows only primary key columns and any columns with data changes."
complete -c dolt -n "__fish_seen_subcommand_from diff" -s ic -l include-cols -d "A list of columns to include in the diff."
complete -c dolt -n "__fish_seen_subcommand_from diff" -s d -l data -d "Show only the data changes, do not show the schema changes (Both shown by default)."
complete -c dolt -n "__fish_seen_subcommand_from diff" -s s -l schema -d "Show only the schema changes, do not show the data changes (Both shown by default)."
complete -c dolt -n "__fish_seen_subcommand_from diff" -s r -l result-format -d "How to format diff output. Valid values are tabular, sql, json. Defaults to tabular."
complete -c dolt -n "__fish_seen_subcommand_from diff" -s c -l cached -d "Synonym for --staged"
complete -c dolt -n "__fish_seen_subcommand_from diff" -s R -l reverse -d "Reverses the direction of the diff."
complete -c dolt -n "__fish_seen_subcommand_from diff" -l stat -d "Show stats of data changes"
complete -c dolt -n "__fish_seen_subcommand_from diff" -l summary -d "Show summary of data and schema changes"
complete -c dolt -n "__fish_seen_subcommand_from diff" -l where -d "filters columns based on values in the diff.  See dolt diff --help for details."
complete -c dolt -n "__fish_seen_subcommand_from diff" -l limit -d "limits to the first N diffs."
complete -c dolt -n "__fish_seen_subcommand_from diff" -l filter -d "filters results based on the type of change (added, modified, renamed, dropped). 'removed' is accepted as an alias for 'dropped'."
complete -c dolt -n "__fish_seen_subcommand_from diff" -l staged -d "Show only the staged data changes."
complete -c dolt -n "__fish_seen_subcommand_from diff" -l merge-base -d "Uses merge base of the first commit and second commit (or HEAD if not supplied) as the first commit"
complete -c dolt -n "__fish_seen_subcommand_from diff" -l diff-mode -d "Determines how to display modified rows with tabular output. Valid values are row, line, in-place, context. Defaults to context."
complete -c dolt -n "__fish_seen_subcommand_from diff" -l name-only -d "Only shows table names."
complete -c dolt -n "__fish_seen_subcommand_from diff" -l system -d "Show system tables in addition to user tables"
complete -c dolt -n __fish_use_subcommand -a reset -d "Remove table changes from the list of staged table changes."
complete -c dolt -n "__fish_seen_subcommand_from reset" -l hard -d "Resets the working tables and staged tables. Any changes to tracked tables in the working tree since commit are discarded."
complete -c dolt -n "__fish_seen_subcommand_from reset" -l soft -d "Does not touch the working tables, but removes all tables staged to be committed."
complete -c dolt -n __fish_use_subcommand -a clean -d "Remove untracked tables from working set."
complete -c dolt -n "__fish_seen_subcommand_from clean" -s x -l x -d "Do not respect dolt_ignore; remove untracked tables that match dolt_ignore. dolt_nonlocal_tables is always respected."
complete -c dolt -n "__fish_seen_subcommand_from clean" -l dry-run -d "Tests removing untracked tables without modifying the working set."
complete -c dolt -n __fish_use_subcommand -a commit -d "Record changes to the repository."
complete -c dolt -n "__fish_seen_subcommand_from commit" -s m -l message -d "Use the given msg as the commit message."
complete -c dolt -n "__fish_seen_subcommand_from commit" -s f -l force -d "Ignores any foreign key warnings and proceeds with the commit."
complete -c dolt -n "__fish_seen_subcommand_from commit" -s a -l all -d "Adds all existing, changed tables (but not new tables) in the working set to the staged set."
complete -c dolt -n "__fish_seen_subcommand_from commit" -s A -l ALL -d "Adds all tables and databases (including new tables) in the working set to the staged set."
complete -c dolt -n "__fish_seen_subcommand_from commit" -s S -l gpg-sign -d "Sign the commit using GPG. If no key-id is provided the key-id is taken from 'user.signingkey' the in the configuration"
complete -c dolt -n "__fish_seen_subcommand_from commit" -l allow-empty -d "Allow recording a commit that has the exact same data as its sole parent. This is usually a mistake, so it is disabled by default. This option bypasses that safety. Cannot be used with --skip-empty."
complete -c dolt -n "__fish_seen_subcommand_from commit" -l skip-empty -d "Only create a commit if there are staged changes. If no changes are staged, the call to commit is a no-op. Cannot be used with --allow-empty."
complete -c dolt -n "__fish_seen_subcommand_from commit" -l date -d "Specify the date used in the commit. If not specified the current system time is used."
complete -c dolt -n "__fish_seen_subcommand_from commit" -l author -d "Specify an explicit author using the standard A U Thor author@example.com format."
complete -c dolt -n "__fish_seen_subcommand_from commit" -l amend -d "Amend previous commit"
complete -c dolt -n "__fish_seen_subcommand_from commit" -l skip-verification -d "Skip commit verification"
complete -c dolt -n __fish_use_subcommand -a sql -d "Run a SQL query against tables in repository."
complete -c dolt -n "__fish_seen_subcommand_from sql" -s q -l query -d "Runs a single query and exits."
complete -c dolt -n "__fish_seen_subcommand_from sql" -s r -l result-format -d "How to format result output. Valid values are tabular, csv, json, vertical, and parquet. Defaults to tabular."
complete -c dolt -n "__fish_seen_subcommand_from sql" -s s -l save -d "Used with --query, save the query to the query catalog with the name provided. Saved queries can be examined in the dolt_query_catalog system table."
complete -c dolt -n "__fish_seen_subcommand_from sql" -s x -l execute -d "Executes a saved query with the given name."
complete -c dolt -n "__fish_seen_subcommand_from sql" -s l -l list-saved -d "List all saved queries."
complete -c dolt -n "__fish_seen_subcommand_from sql" -s m -l message -d "Used with --query and --save, saves the query with the descriptive message given. See also `--name`."
complete -c dolt -n "__fish_seen_subcommand_from sql" -s b -l batch -d "Use to enable more efficient batch processing for large SQL import scripts. This mode is no longer supported and this flag is a no-op. To speed up your SQL imports, use either LOAD DATA, or structure your SQL import script to insert many rows per statement."
complete -c dolt -n "__fish_seen_subcommand_from sql" -s c -l continue -d "Continue running queries on an error. Used for batch mode only."
complete -c dolt -n "__fish_seen_subcommand_from sql" -s f -l file -d "Execute statements from the file given."
complete -c dolt -n "__fish_seen_subcommand_from sql" -l binary-as-hex -d "Print binary data as hex. Enabled by default for interactive terminals."
complete -c dolt -n "__fish_seen_subcommand_from sql" -l skip-binary-as-hex -d "Disable binary data as hex output."
complete -c dolt -n "__fish_seen_subcommand_from sql" -l disable-auto-gc -d "Disable automatically running GC."
complete -c dolt -n __fish_use_subcommand -a sql-server -d "Start a MySQL-compatible server."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -s H -l host -d "Defines the host address that the server will run on. Defaults to `localhost`."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -s P -l port -d "Defines the port that the server will run on. Defaults to `3306`."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -s u -l user -d "This option is no longer supported. Instead, you can create users using CREATE USER and GRANT SQL statements."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -s p -l password -d "This option is no longer supported. Instead, you can create users using CREATE USER and GRANT SQL statements."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -s t -l timeout -d "Defines the timeout, in seconds, used for connections"
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -s r -l readonly -d "Disable modification of the database."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -s l -l loglevel -d "Defines the level of logging provided"
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -s f -l logformat -d "Defines the output format of the server log"
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l config -d "When provided configuration is taken from the yaml config file and all command line parameters are ignored."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l skip-root-user-initialization -d "Skips the automatic creation of a default root super user on the first launch of a SQL server."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l data-dir -d "Defines a directory to find databases to serve. Defaults to the current directory."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l multi-db-dir -d "Deprecated, use `--data-dir` instead."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l doltcfg-dir -d "Defines a directory that contains non-database storage for dolt. Defaults to `$data-dir/.doltcfg`. Will be created automatically as needed."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l no-auto-commit -d "Set @@autocommit = off for the server."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l query-parallelism -d "Deprecated, no effect in current versions of Dolt"
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l max-connections -d "Set the number of connections handled by the server. Defaults to `1000`."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l back-log -d "Set the number of connections that can block waiting for a connection before new connections are rejected. Defaults to `50`."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l max-connections-timeout -d "Set the maximum duration that a connection will block waiting for a connection before being rejected. Defaults to `1m0s`."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l privilege-file -d "Path to a file to load and store users and grants. Defaults to `$doltcfg-dir/privileges.db`. Will be created as needed."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l branch-control-file -d "Path to a file to load and store branch control permissions. Defaults to `$doltcfg-dir/branch_control.db`. Will be created as needed."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l allow-cleartext-passwords -d "Allows use of cleartext passwords. Defaults to false."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l socket -d "Path for the unix socket file. Defaults to '/tmp/mysql.sock'."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l remotesapi-port -d "Sets the port for a server which can expose the databases in this sql-server over remotesapi, so that clients can clone or pull from this server."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l remotesapi-readonly -d "Disable writes to the sql-server via the push operations. SQL writes are unaffected by this setting."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l golden -d "Provides a connection string to a MySQL instance to be used to validate query results"
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l event-scheduler -d "Determines whether the Event Scheduler is enabled and running on the server. It has one of the following values: 'ON', 'OFF' or 'DISABLED'."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l mcp-port -d "If provided, runs a Dolt MCP HTTP server on this port alongside the sql-server."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l mcp-user -d "SQL user for MCP to connect as (required when --mcp-port is set)."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l mcp-password -d "Optional SQL password for MCP to connect with (requires --mcp-user)."
complete -c dolt -n "__fish_seen_subcommand_from sql-server" -l mcp-database -d "Optional SQL database name MCP should connect to (requires --mcp-port and --mcp-user)."
complete -c dolt -n __fish_use_subcommand -a log -d "Show commit logs."
complete -c dolt -n "__fish_seen_subcommand_from log" -s n -l number -d "Limit the number of commits to output."
complete -c dolt -n "__fish_seen_subcommand_from log" -l min-parents -d "The minimum number of parents a commit must have to be included in the log."
complete -c dolt -n "__fish_seen_subcommand_from log" -l merges -d "Equivalent to min-parents == 2, this will limit the log to commits with 2 or more parents."
complete -c dolt -n "__fish_seen_subcommand_from log" -l parents -d "Shows all parents of each commit in the log."
complete -c dolt -n "__fish_seen_subcommand_from log" -l decorate -d "Shows refs next to commits. Valid options are short, full, no, and auto"
complete -c dolt -n "__fish_seen_subcommand_from log" -l not -d "Excludes commits from revision."
complete -c dolt -n "__fish_seen_subcommand_from log" -l all -d "Automatically select every branch in database"
complete -c dolt -n "__fish_seen_subcommand_from log" -l show-signature -d "Shows the signature of each commit."
complete -c dolt -n "__fish_seen_subcommand_from log" -l oneline -d "Shows logs in a compact format."
complete -c dolt -n "__fish_seen_subcommand_from log" -l stat -d "Shows the diffstat for each commit."
complete -c dolt -n "__fish_seen_subcommand_from log" -l graph -d "Shows the commit graph."
complete -c dolt -n __fish_use_subcommand -a show -d "Show information about a specific commit."
complete -c dolt -n "__fish_seen_subcommand_from show" -s d -l data -d "Show only the data changes, do not show the schema changes (Both shown by default)."
complete -c dolt -n "__fish_seen_subcommand_from show" -s s -l schema -d "Show only the schema changes, do not show the data changes (Both shown by default)."
complete -c dolt -n "__fish_seen_subcommand_from show" -s r -l result-format -d "How to format diff output. Valid values are tabular, sql, json. Defaults to tabular."
complete -c dolt -n "__fish_seen_subcommand_from show" -s c -l cached -d "Show only the staged data changes."
complete -c dolt -n "__fish_seen_subcommand_from show" -s sk -l skinny -d "Shows only primary key columns and any columns with data changes."
complete -c dolt -n "__fish_seen_subcommand_from show" -l parents -d "Shows all parents of each commit in the log."
complete -c dolt -n "__fish_seen_subcommand_from show" -l decorate -d "Shows refs next to commits. Valid options are short, full, no, and auto"
complete -c dolt -n "__fish_seen_subcommand_from show" -l no-pretty -d "Show the object without making it pretty."
complete -c dolt -n "__fish_seen_subcommand_from show" -l stat -d "Show stats of data changes"
complete -c dolt -n "__fish_seen_subcommand_from show" -l summary -d "Show summary of data and schema changes"
complete -c dolt -n "__fish_seen_subcommand_from show" -l where -d "filters columns based on values in the diff.  See dolt diff --help for details."
complete -c dolt -n "__fish_seen_subcommand_from show" -l limit -d "limits to the first N diffs."
complete -c dolt -n "__fish_seen_subcommand_from show" -l merge-base -d "Uses merge base of the first commit and second commit (or HEAD if not supplied) as the first commit"
complete -c dolt -n "__fish_seen_subcommand_from show" -l diff-mode -d "Determines how to display modified rows with tabular output. Valid values are row, line, in-place, context. Defaults to context."
complete -c dolt -n __fish_use_subcommand -a branch -d "Create, list, edit, delete branches."
complete -c dolt -n "__fish_seen_subcommand_from branch" -s f -l force -d "Reset branchname to startpoint, even if branchname exists already. Without -f, dolt branch refuses to change an existing branch. In combination with -d (or --delete), allow deleting the branch irrespective of its merged status. In combination with -m (or --move), allow renaming the branch even if the new branch name already exists, the same applies for -c (or --copy)."
complete -c dolt -n "__fish_seen_subcommand_from branch" -s c -l copy -d "Create a copy of a branch."
complete -c dolt -n "__fish_seen_subcommand_from branch" -s m -l move -d "Move/rename a branch"
complete -c dolt -n "__fish_seen_subcommand_from branch" -s d -l delete -d "Delete a branch. The branch must be fully merged in its upstream branch."
complete -c dolt -n "__fish_seen_subcommand_from branch" -s t -l track -d "Set up upstream configuration for a branch. Uses current branch as default"
complete -c dolt -n "__fish_seen_subcommand_from branch" -s u -l set-upstream-to -d "Set upstream configuration for a branch."
complete -c dolt -n "__fish_seen_subcommand_from branch" -s v -l verbose -d "When in list mode, show the hash and commit subject line for each head, along with relationship to upstream branch (if any). If given twice, print the name of the upstream branch as well"
complete -c dolt -n "__fish_seen_subcommand_from branch" -s a -l all -d "When in list mode, shows remote tracked branches"
complete -c dolt -n "__fish_seen_subcommand_from branch" -s r -l remote -d "When in list mode, show only remote tracked branches. When with -d, delete a remote tracking branch."
complete -c dolt -n "__fish_seen_subcommand_from branch" -l D -d "Shortcut for --delete --force."
complete -c dolt -n "__fish_seen_subcommand_from branch" -l list -d "List branches"
complete -c dolt -n "__fish_seen_subcommand_from branch" -l datasets -d "List all datasets in the database"
complete -c dolt -n "__fish_seen_subcommand_from branch" -l show-current -d "Print the name of the current branch"
complete -c dolt -n __fish_use_subcommand -a checkout -d "Checkout a branch or overwrite a table from HEAD."
complete -c dolt -n "__fish_seen_subcommand_from checkout" -s f -l force -d "If there is any changes in working set, the force flag will wipe out the current changes and checkout the new branch."
complete -c dolt -n "__fish_seen_subcommand_from checkout" -s t -l track -d "When creating a new branch, set up 'upstream' configuration."
complete -c dolt -n "__fish_seen_subcommand_from checkout" -l b -d "Create a new branch named new_branch and start it at start_point."
complete -c dolt -n "__fish_seen_subcommand_from checkout" -l B -d "Similar to '-b'. Forcibly resets the branch to start_point if it exists."
complete -c dolt -n __fish_use_subcommand -a merge -d "Merge a branch."
complete -c dolt -n "__fish_seen_subcommand_from merge" -s m -l message -d "Use the given msg as the commit message."
complete -c dolt -n "__fish_seen_subcommand_from merge" -l no-ff -d "Create a merge commit even when the merge resolves as a fast-forward."
complete -c dolt -n "__fish_seen_subcommand_from merge" -l ff-only -d "Refuse to merge unless the current HEAD is already up to date or the merge can be resolved as a fast-forward."
complete -c dolt -n "__fish_seen_subcommand_from merge" -l squash -d "Merge changes to the working set without updating the commit history"
complete -c dolt -n "__fish_seen_subcommand_from merge" -l abort -d "Abort the in-progress merge and return the working set to the state before the merge started."
complete -c dolt -n "__fish_seen_subcommand_from merge" -l commit -d "Perform the merge and commit the result. This is the default option, but can be overridden with the --no-commit flag. Note that this option does not affect fast-forward merges, which don't create a new merge commit, and if any merge conflicts or constraint violations are detected, no commit will be attempted."
complete -c dolt -n "__fish_seen_subcommand_from merge" -l no-commit -d "Perform the merge and stop just before creating a merge commit. Note this will not prevent a fast-forward merge; use the --no-ff arg together with the --no-commit arg to prevent both fast-forwards and merge commits."
complete -c dolt -n "__fish_seen_subcommand_from merge" -l no-edit -d "Use an auto-generated commit message when creating a merge commit. The default for interactive CLI sessions is to open an editor."
complete -c dolt -n "__fish_seen_subcommand_from merge" -l author -d "Specify an explicit author using the standard A U Thor author@example.com format."
complete -c dolt -n "__fish_seen_subcommand_from merge" -l skip-verification -d "Skip commit verification before merge"
complete -c dolt -n __fish_use_subcommand -a conflicts -d "Commands for viewing and resolving merge conflicts."
complete -c dolt -n "__fish_seen_subcommand_from conflicts" -a cat -d "Writes out the table conflicts."
complete -c dolt -n "__fish_seen_subcommand_from conflicts" -a resolve -d "Removes rows from list of conflicts"
complete -c dolt -n "__fish_seen_subcommand_from conflicts; and __fish_seen_subcommand_from resolve" -l ours -d "For all conflicts, take the version from our branch and resolve the conflict"
complete -c dolt -n "__fish_seen_subcommand_from conflicts; and __fish_seen_subcommand_from resolve" -l theirs -d "For all conflicts, take the version from their branch and resolve the conflict"
complete -c dolt -n __fish_use_subcommand -a cherry-pick -d "Apply the changes introduced by an existing commit."
complete -c dolt -n "__fish_seen_subcommand_from cherry-pick" -l abort -d "Abort the current conflict resolution process, and revert all changes from the in-process cherry-pick operation."
complete -c dolt -n "__fish_seen_subcommand_from cherry-pick" -l allow-empty -d "Allow empty commits to be cherry-picked. Note that use of this option only keeps commits that were initially empty. Commits which become empty, due to a previous commit, will cause cherry-pick to fail."
complete -c dolt -n "__fish_seen_subcommand_from cherry-pick" -l skip-verification -d "Skip commit verification before cherry-pick"
complete -c dolt -n __fish_use_subcommand -a revert -d "Undo the changes introduced in a commit."
complete -c dolt -n "__fish_seen_subcommand_from revert" -l author -d "Specify an explicit author using the standard A U Thor author@example.com format."
complete -c dolt -n __fish_use_subcommand -a clone -d "Clone from a remote data repository."
complete -c dolt -n "__fish_seen_subcommand_from clone" -s b -l branch -d "The branch to be cloned. If not specified all branches will be cloned."
complete -c dolt -n "__fish_seen_subcommand_from clone" -s u -l user -d "User name to use when authenticating with the remote. Gets password from the environment variable DOLT_REMOTE_PASSWORD."
complete -c dolt -n "__fish_seen_subcommand_from clone" -l remote -d "Name of the remote to be added to the cloned database. The default is 'origin'."
complete -c dolt -n "__fish_seen_subcommand_from clone" -l depth -d "Clone a single branch and limit history to the given commit depth."
complete -c dolt -n "__fish_seen_subcommand_from clone" -l ref -d "Git ref to use as the Dolt data ref for git remotes (default: refs/dolt/data)."
complete -c dolt -n "__fish_seen_subcommand_from clone" -l aws-creds-file -d "AWS credentials file."
complete -c dolt -n "__fish_seen_subcommand_from clone" -l aws-creds-profile -d "AWS profile to use."
complete -c dolt -n "__fish_seen_subcommand_from clone" -l oss-creds-file -d "OSS credentials file."
complete -c dolt -n "__fish_seen_subcommand_from clone" -l oss-creds-profile -d "OSS profile to use."
complete -c dolt -n "__fish_seen_subcommand_from clone" -l single-branch -d "Clone only the history leading to the tip of a single branch, either specified by --branch or the remote's HEAD (default)."
complete -c dolt -n "__fish_seen_subcommand_from clone" -l aws-region -d "No description"
complete -c dolt -n "__fish_seen_subcommand_from clone" -l aws-creds-type -d "No description"
complete -c dolt -n __fish_use_subcommand -a fetch -d "Update the database from a remote data repository."
complete -c dolt -n "__fish_seen_subcommand_from fetch" -s p -l prune -d "After fetching, remove any remote-tracking references that don't exist on the remote."
complete -c dolt -n "__fish_seen_subcommand_from fetch" -l user -d "User name to use when authenticating with the remote. Gets password from the environment variable DOLT_REMOTE_PASSWORD."
complete -c dolt -n "__fish_seen_subcommand_from fetch" -l silent -d "Suppress progress information."
complete -c dolt -n __fish_use_subcommand -a pull -d "Fetch from a dolt remote data repository and merge."
complete -c dolt -n "__fish_seen_subcommand_from pull" -s f -l force -d "Update from the remote HEAD even if there are errors."
complete -c dolt -n "__fish_seen_subcommand_from pull" -s p -l prune -d "After fetching, remove any remote-tracking references that don't exist on the remote."
complete -c dolt -n "__fish_seen_subcommand_from pull" -l squash -d "Merge changes to the working set without updating the commit history"
complete -c dolt -n "__fish_seen_subcommand_from pull" -l no-ff -d "Create a merge commit even when the merge resolves as a fast-forward."
complete -c dolt -n "__fish_seen_subcommand_from pull" -l ff-only -d "Refuse to merge unless the current HEAD is already up to date or the merge can be resolved as a fast-forward."
complete -c dolt -n "__fish_seen_subcommand_from pull" -l commit -d "Perform the merge and commit the result. This is the default option, but can be overridden with the --no-commit flag. Note that this option does not affect fast-forward merges, which don't create a new merge commit, and if any merge conflicts or constraint violations are detected, no commit will be attempted."
complete -c dolt -n "__fish_seen_subcommand_from pull" -l no-commit -d "Perform the merge and stop just before creating a merge commit. Note this will not prevent a fast-forward merge; use the --no-ff arg together with the --no-commit arg to prevent both fast-forwards and merge commits."
complete -c dolt -n "__fish_seen_subcommand_from pull" -l no-edit -d "Use an auto-generated commit message when creating a merge commit. The default for interactive CLI sessions is to open an editor."
complete -c dolt -n "__fish_seen_subcommand_from pull" -l user -d "User name to use when authenticating with the remote. Gets password from the environment variable DOLT_REMOTE_PASSWORD."
complete -c dolt -n "__fish_seen_subcommand_from pull" -l silent -d "Suppress progress information."
complete -c dolt -n "__fish_seen_subcommand_from pull" -l skip-verification -d "Skip commit verification before merge"
complete -c dolt -n __fish_use_subcommand -a push -d "Push to a dolt remote."
complete -c dolt -n "__fish_seen_subcommand_from push" -s u -l set-upstream -d "For every branch that is up to date or successfully pushed, add upstream (tracking) reference, used by argument-less dolt pull and other commands."
complete -c dolt -n "__fish_seen_subcommand_from push" -s f -l force -d "Update the remote with local history, overwriting any conflicting history in the remote."
complete -c dolt -n "__fish_seen_subcommand_from push" -l user -d "User name to use when authenticating with the remote. Gets password from the environment variable DOLT_REMOTE_PASSWORD."
complete -c dolt -n "__fish_seen_subcommand_from push" -l all -d "Push all branches."
complete -c dolt -n "__fish_seen_subcommand_from push" -l silent -d "Suppress progress information."
complete -c dolt -n __fish_use_subcommand -a config -d "Dolt configuration."
complete -c dolt -n "__fish_seen_subcommand_from config" -l global -d "Use global config."
complete -c dolt -n "__fish_seen_subcommand_from config" -l local -d "Use repository local config."
complete -c dolt -n "__fish_seen_subcommand_from config" -l add -d "Set the value of one or more config parameters"
complete -c dolt -n "__fish_seen_subcommand_from config" -l set -d "Set the value of one or more config parameters"
complete -c dolt -n "__fish_seen_subcommand_from config" -l list -d "List the values of all config parameters."
complete -c dolt -n "__fish_seen_subcommand_from config" -l get -d "Get the value of one or more config parameters."
complete -c dolt -n "__fish_seen_subcommand_from config" -l unset -d "Unset the value of one or more config parameters."
complete -c dolt -n __fish_use_subcommand -a remote -d "Manage set of tracked repositories."
complete -c dolt -n "__fish_seen_subcommand_from remote" -s v -l verbose -d "When printing the list of remotes adds additional details."
complete -c dolt -n "__fish_seen_subcommand_from remote" -l ref -d "Git ref to use as the Dolt data ref for git remotes (default: refs/dolt/data)."
complete -c dolt -n "__fish_seen_subcommand_from remote" -l aws-region -d "Cloud provider region associated with this remote."
complete -c dolt -n "__fish_seen_subcommand_from remote" -l aws-creds-type -d "Credential type. Valid options are role, env, and file. See the help section for additional details."
complete -c dolt -n "__fish_seen_subcommand_from remote" -l aws-creds-file -d "AWS credentials file"
complete -c dolt -n "__fish_seen_subcommand_from remote" -l aws-creds-profile -d "AWS profile to use"
complete -c dolt -n "__fish_seen_subcommand_from remote" -l oss-creds-file -d "OSS credentials file"
complete -c dolt -n "__fish_seen_subcommand_from remote" -l oss-creds-profile -d "OSS profile to use"
complete -c dolt -n __fish_use_subcommand -a backup -d "Manage a set of server backups."
complete -c dolt -n "__fish_seen_subcommand_from backup" -s v -l verbose -d "When printing the list of backups adds additional details."
complete -c dolt -n "__fish_seen_subcommand_from backup" -s f -l force -d "When restoring a backup, overwrite the contents of the existing database with the same name."
complete -c dolt -n "__fish_seen_subcommand_from backup" -l ref -d "Git ref to use as the Dolt data ref for git remotes (default: refs/dolt/data)."
complete -c dolt -n "__fish_seen_subcommand_from backup" -l aws-creds-file -d "AWS credentials file"
complete -c dolt -n "__fish_seen_subcommand_from backup" -l aws-creds-profile -d "AWS profile to use"
complete -c dolt -n "__fish_seen_subcommand_from backup" -l aws-region -d "No description"
complete -c dolt -n "__fish_seen_subcommand_from backup" -l aws-creds-type -d "No description"
complete -c dolt -n __fish_use_subcommand -a login -d "Login to a dolt remote host."
complete -c dolt -n "__fish_seen_subcommand_from login" -s e -l auth-endpoint -d "Specify the endpoint used to authenticate this client. Must be used with --login-url OR set in the configuration file as `creds.add_url`"
complete -c dolt -n "__fish_seen_subcommand_from login" -s url -l login-url -d "Specify the login url where the browser will add credentials."
complete -c dolt -n "__fish_seen_subcommand_from login" -s i -l insecure -d "If set, makes insecure connection to remote authentication server"
complete -c dolt -n __fish_use_subcommand -a creds -d "Commands for managing credentials."
complete -c dolt -n "__fish_seen_subcommand_from creds" -a new -d "Create a new public/private keypair for authenticating with doltremoteapi."
complete -c dolt -n "__fish_seen_subcommand_from creds" -a rm -d "Remove a stored public/private keypair."
complete -c dolt -n "__fish_seen_subcommand_from creds" -a ls -d "List keypairs available for authenticating with doltremoteapi."
complete -c dolt -n "__fish_seen_subcommand_from creds" -a check -d "Check authenticating with a credential keypair against a doltremoteapi."
complete -c dolt -n "__fish_seen_subcommand_from creds; and __fish_seen_subcommand_from check" -l endpoint -d "API endpoint, otherwise taken from config."
complete -c dolt -n "__fish_seen_subcommand_from creds; and __fish_seen_subcommand_from check" -l creds -d "Public Key ID or Public Key for credentials, otherwise taken from config."
complete -c dolt -n "__fish_seen_subcommand_from creds" -a use -d "Select an existing dolt credential for authenticating with doltremoteapi."
complete -c dolt -n "__fish_seen_subcommand_from creds" -a import -d "Import a dolt credential from an existing .jwk file."
complete -c dolt -n "__fish_seen_subcommand_from creds; and __fish_seen_subcommand_from import" -l no-profile -d "If provided, no attempt will be made to contact doltremoteapi and update user.name and user.email."
complete -c dolt -n __fish_use_subcommand -a ls -d "List tables in the working set."
complete -c dolt -n "__fish_seen_subcommand_from ls" -s v -l verbose -d "show the hash of the table and row count"
complete -c dolt -n "__fish_seen_subcommand_from ls" -s s -l system -d "show system tables"
complete -c dolt -n "__fish_seen_subcommand_from ls" -s a -l all -d "show user and system tables"
complete -c dolt -n __fish_use_subcommand -a schema -d "Commands for showing and importing table schemas."
complete -c dolt -n "__fish_seen_subcommand_from schema" -a export -d "Exports a table's schema in SQL form."
complete -c dolt -n "__fish_seen_subcommand_from schema" -a import -d "Creates a new table with an inferred schema."
complete -c dolt -n "__fish_seen_subcommand_from schema" -a show -d "Shows the schema of one or more tables."
complete -c dolt -n "__fish_seen_subcommand_from schema" -a tags -d "Shows the column tags of one or more tables."
complete -c dolt -n "__fish_seen_subcommand_from schema" -a update-tag -d "Update a column's tag"
complete -c dolt -n __fish_use_subcommand -a table -d "Commands for copying, renaming, deleting, and exporting tables."
complete -c dolt -n "__fish_seen_subcommand_from table" -a import -d "Creates, overwrites, replaces, or updates a table from the data in a file."
complete -c dolt -n "__fish_seen_subcommand_from table" -a export -d "Export a table to a file."
complete -c dolt -n "__fish_seen_subcommand_from table" -a rm -d "Deletes a table"
complete -c dolt -n "__fish_seen_subcommand_from table" -a mv -d "Moves a table"
complete -c dolt -n "__fish_seen_subcommand_from table" -a cp -d "Copies a table"
complete -c dolt -n __fish_use_subcommand -a tag -d "Create, list, delete tags."
complete -c dolt -n "__fish_seen_subcommand_from tag" -s m -l message -d "Use the given msg as the tag message."
complete -c dolt -n "__fish_seen_subcommand_from tag" -s v -l verbose -d "list tags along with their metadata."
complete -c dolt -n "__fish_seen_subcommand_from tag" -s d -l delete -d "Delete a tag."
complete -c dolt -n "__fish_seen_subcommand_from tag" -l author -d "Specify an explicit author using the standard A U Thor author@example.com format."
complete -c dolt -n __fish_use_subcommand -a blame -d "Show what revision and author last modified each row of a table."
complete -c dolt -n __fish_use_subcommand -a constraints -d "Commands for handling constraints."
complete -c dolt -n "__fish_seen_subcommand_from constraints" -a verify -d "Command to verify that the constraints on the given table(s) are satisfied."
complete -c dolt -n __fish_use_subcommand -a read-tables -d "Fetch table(s) at a specific commit into a new dolt repo"
complete -c dolt -n "__fish_seen_subcommand_from read-tables" -s d -l dir -d "directory to create and put retrieved table data."
complete -c dolt -n "__fish_seen_subcommand_from read-tables" -l ref -d "Git ref to use as the Dolt data ref for git remotes (default: refs/dolt/data)."
complete -c dolt -n __fish_use_subcommand -a gc -d "Cleans up unreferenced data from the repository."
complete -c dolt -n "__fish_seen_subcommand_from gc" -s s -l shallow -d "perform a fast, but incomplete garbage collection pass"
complete -c dolt -n "__fish_seen_subcommand_from gc" -s f -l full -d "perform a full garbage collection, including the old generation"
complete -c dolt -n "__fish_seen_subcommand_from gc" -l archive-level -d "Specify the archive compression level garbage collection results. Default is 1, Disable with 0"
complete -c dolt -n __fish_use_subcommand -a fsck -d "Verifies the contents of the database are not corrupted. Provides repair when possible."
complete -c dolt -n "__fish_seen_subcommand_from fsck" -l quiet -d "Don't show progress. Just print final report."
complete -c dolt -n "__fish_seen_subcommand_from fsck" -l revive-journal-with-data-loss -d "Revives a corrupted chunk journal by discarding unparsable data."
complete -c dolt -n __fish_use_subcommand -a filter-branch -d "Edits the commit history using the provided query."
complete -c dolt -n "__fish_seen_subcommand_from filter-branch" -s v -l verbose -d "logs more information"
complete -c dolt -n "__fish_seen_subcommand_from filter-branch" -s b -l branches -d "filter all branches"
complete -c dolt -n "__fish_seen_subcommand_from filter-branch" -s a -l all -d "filter all branches and tags"
complete -c dolt -n "__fish_seen_subcommand_from filter-branch" -s c -l continue -d "log a warning and continue if any errors occur executing statements"
complete -c dolt -n "__fish_seen_subcommand_from filter-branch" -s q -l query -d "Queries to run, separated by semicolons. If not provided, queries are read from STDIN."
complete -c dolt -n "__fish_seen_subcommand_from filter-branch" -l apply-to-uncommitted -d "apply changes to uncommitted tables"
complete -c dolt -n __fish_use_subcommand -a merge-base -d "Find the common ancestor of two commits."
complete -c dolt -n __fish_use_subcommand -a version -d "Displays the version for the Dolt binary."
complete -c dolt -n "__fish_seen_subcommand_from version" -s f -l feature -d "display the feature version of this repository."
complete -c dolt -n "__fish_seen_subcommand_from version" -s v -l verbose -d "display verbose details, including the storage format of this repository."
complete -c dolt -n __fish_use_subcommand -a dump -d "Export all tables in the working set into a file."
complete -c dolt -n "__fish_seen_subcommand_from dump" -s r -l result-format -d "Define the type of the output file. Defaults to sql. Valid values are sql, csv, json and parquet."
complete -c dolt -n "__fish_seen_subcommand_from dump" -s fn -l file-name -d "Define file name for dump file. Defaults to `doltdump.sql`."
complete -c dolt -n "__fish_seen_subcommand_from dump" -s d -l directory -d "Define directory name to dump the files in. Defaults to `doltdump/`."
complete -c dolt -n "__fish_seen_subcommand_from dump" -s f -l force -d "If data already exists in the destination, the force flag will allow the target to be overwritten."
complete -c dolt -n "__fish_seen_subcommand_from dump" -s na -l no-autocommit -d "Turn off autocommit for each dumped table. Useful for speeding up loading of output SQL file."
complete -c dolt -n "__fish_seen_subcommand_from dump" -l batch -d "Return batch insert statements wherever possible, enabled by default."
complete -c dolt -n "__fish_seen_subcommand_from dump" -l no-batch -d "Emit one row per statement, instead of batching multiple rows into each statement."
complete -c dolt -n "__fish_seen_subcommand_from dump" -l schema-only -d "Dump a table's schema, without including any data, to the output SQL file."
complete -c dolt -n "__fish_seen_subcommand_from dump" -l no-create-db -d "Do not write `CREATE DATABASE` statements in SQL files."
complete -c dolt -n __fish_use_subcommand -a docs -d "Commands for working with Dolt documents."
complete -c dolt -n "__fish_seen_subcommand_from docs" -a diff -d "Diffs Dolt Docs"
complete -c dolt -n "__fish_seen_subcommand_from docs" -a print -d "Prints Dolt Docs to stdout"
complete -c dolt -n "__fish_seen_subcommand_from docs" -a upload -d "Uploads Dolt Docs from the file system into the database"
complete -c dolt -n __fish_use_subcommand -a stash -d "Stash the changes in a dirty workspace away."
complete -c dolt -n "__fish_seen_subcommand_from stash" -s u -l include-untracked -d "Untracked tables are also stashed."
complete -c dolt -n "__fish_seen_subcommand_from stash" -s a -l all -d "All tables are stashed, including untracked and ignored tables."
complete -c dolt -n __fish_use_subcommand -a profile -d "Manage dolt profiles for CLI global options."
complete -c dolt -n "__fish_seen_subcommand_from profile" -s u -l user -d "Defines the local superuser (defaults to `root`). If the specified user exists, will take on permissions of that user."
complete -c dolt -n "__fish_seen_subcommand_from profile" -s p -l password -d "Defines the password for the user. Defaults to empty string when the user is `root`."
complete -c dolt -n "__fish_seen_subcommand_from profile" -s v -l verbose -d "Includes full details when printing list of profiles."
complete -c dolt -n "__fish_seen_subcommand_from profile" -l host -d "Defines the host to connect to."
complete -c dolt -n "__fish_seen_subcommand_from profile" -l port -d "Defines the port to connect to."
complete -c dolt -n "__fish_seen_subcommand_from profile" -l no-tls -d "Disables TLS for the connection to remote databases."
complete -c dolt -n "__fish_seen_subcommand_from profile" -l data-dir -d "Defines a data directory whose subdirectories should all be dolt data repositories accessible as independent databases. Defaults to the current directory."
complete -c dolt -n "__fish_seen_subcommand_from profile" -l doltcfg-dir -d "Defines a directory that contains configuration files for dolt. Defaults to `$data-dir/.doltcfg`. Will only be created if there is a change to configuration settings."
complete -c dolt -n "__fish_seen_subcommand_from profile" -l privilege-file -d "Path to a file to load and store users and grants. Defaults to `$doltcfg-dir/privileges.db`. Will only be created if there is a change to privileges."
complete -c dolt -n "__fish_seen_subcommand_from profile" -l branch-control-file -d "Path to a file to load and store branch control permissions. Defaults to `$doltcfg-dir/branch_control.db`. Will only be created if there is a change to branch control permissions."
complete -c dolt -n "__fish_seen_subcommand_from profile" -l use-db -d "The name of the database to use when executing SQL queries. Defaults the database of the root directory, if it exists, and the first alphabetically if not."
complete -c dolt -n "__fish_seen_subcommand_from profile" -l branch -d "Name of the branch to be selected"
complete -c dolt -n __fish_use_subcommand -a query-diff -d "Shows table diff between two queries."
complete -c dolt -n __fish_use_subcommand -a reflog -d "Show history of named refs."
complete -c dolt -n "__fish_seen_subcommand_from reflog" -l all -d "Show all refs, including hidden refs, such as DoltHub workspace refs"
complete -c dolt -n __fish_use_subcommand -a rebase -d "Reapplies commits on top of another base tip"
complete -c dolt -n "__fish_seen_subcommand_from rebase" -s i -l interactive -d "Start an interactive rebase"
complete -c dolt -n "__fish_seen_subcommand_from rebase" -l empty -d "How to handle commits that are not empty to start, but which become empty after rebasing. Valid values are: drop (default) or keep"
complete -c dolt -n "__fish_seen_subcommand_from rebase" -l abort -d "Abort an interactive rebase and return the working set to the pre-rebase state"
complete -c dolt -n "__fish_seen_subcommand_from rebase" -l continue -d "Continue an interactive rebase after adjusting the rebase plan"
complete -c dolt -n "__fish_seen_subcommand_from rebase" -l skip-verification -d "Skip commit verification before rebase"
complete -c dolt -n __fish_use_subcommand -a ci -d "Commands for working with Dolt continuous integration configuration."
complete -c dolt -n "__fish_seen_subcommand_from ci" -a init -d "Creates database tables used to store continuous integration configuration"
complete -c dolt -n "__fish_seen_subcommand_from ci" -a destroy -d "Drops all database tables used to store continuous integration configuration"
complete -c dolt -n "__fish_seen_subcommand_from ci" -a import -d "Import a Dolt continuous integration workflow file into the database"
complete -c dolt -n "__fish_seen_subcommand_from ci" -a export -d "Export a Dolt continuous integration workflow by name"
complete -c dolt -n "__fish_seen_subcommand_from ci" -a ls -d "List Dolt continuous integration workflows"
complete -c dolt -n "__fish_seen_subcommand_from ci" -a remove -d "Removes a Dolt continuous integration workflow by name"
complete -c dolt -n "__fish_seen_subcommand_from ci" -a view -d "View details of a specific Dolt CI workflow"
complete -c dolt -n "__fish_seen_subcommand_from ci" -a run -d "Run a Dolt CI workflow"
complete -c dolt -n __fish_use_subcommand -a debug -d "Run a query in profile and trace mode"
complete -c dolt -n "__fish_seen_subcommand_from debug" -s q -l query -d "Runs a single query and exits."
complete -c dolt -n "__fish_seen_subcommand_from debug" -s r -l result-format -d "How to format result output. Valid values are tabular, csv, json, vertical, and parquet. Defaults to tabular."
complete -c dolt -n "__fish_seen_subcommand_from debug" -s c -l continue -d "Continue running queries on an error. Used for batch mode only."
complete -c dolt -n "__fish_seen_subcommand_from debug" -s f -l file -d "Execute statements from the file given."
complete -c dolt -n "__fish_seen_subcommand_from debug" -s t -l time -d "Execute for at least time seconds."
complete -c dolt -n "__fish_seen_subcommand_from debug" -s o -l output -d "Result directory (Defaults to temporary director)"
complete -c dolt -n __fish_use_subcommand -a rm -d "Drops a table and removes it from tracking"
complete -c dolt -n "__fish_seen_subcommand_from rm" -l cached -d "Use this option to unstage and remove tables only from the index. Working tree tables, whether modified or not, will be left alone."
