# Application bindings
$terminal = uwsm app -- wezterm start --always-new-process
$browser = uwsm app brave --new-window --ozone-platform=wayland
$webapp = $browser --app

bindd = SUPER, Q, Close active window, killactive,
bindd = SUPER, X, Terminal, exec, $terminal
bindd = SUPER, F, Force full screen, fullscreen, 0
bindd = SUPER, E, File manager, exec, uwsm app -- thunar
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, M, Music, exec, $webapp="https://music.youtube.com/"
bindd = SUPER, N, Neovim, exec, $terminal -e nvim
bindd = SUPER, T, Activity, exec, $terminal -e btop
bindd = SUPER, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER, G, Signal, exec, uwsm app -- signal-desktop
bindd = SUPER, O, Obsidian, exec, uwsm app -- obsidian -disable-gpu

# bindd = SUPER, A, ChatGPT, exec, $webapp="https://chatgpt.com"
# bindd = SUPER SHIFT, A, Grok, exec, $webapp="https://grok.com"
# bindd = SUPER, Y, YouTube, exec, $webapp="https://youtube.com/"
# bindd = SUPER ALT, G, Google Messages, exec, $webapp="https://messages.google.com/web/conversations"
# bindd = SUPER SHIFT, X, X Post, exec, $webapp="https://x.com/compose/post"


bindd = SUPER ALT, SPACE, Omarchy menu, exec, ~/.local/share/omarchy/bin/omarchy-menu
bindd = SUPER, ESCAPE, Power menu, exec, ~/.local/share/omarchy/bin/omarchy-menu system
