model_list:
  # https://docs.litellm.ai/docs/providers/mistral
  - model_name: codestral
    litellm_params:
      model: "mistral/codestral-latest"
      api_key: "os.environ/CODESTRAL_API_KEY"
      api_base: "https://codestral.mistral.ai"
      api_version: "v1"
      temperature: 0.2
  - model_name: mistral-small
    litellm_params:
      model: "mistral/mistral-small"
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-medium
    litellm_params:
      model: "mistral/mistral-medium"
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-large-latest
    litellm_params:
      model: "mistral/mistral-large-latest"
      api_key: "os.environ/MISTRAL_API_KEY"
