model_list:
  # https://docs.litellm.ai/docs/providers/mistral
  - model_name: mistral-small
    litellm_params:
      model: "mistral/mistral-small"
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-medium
    litellm_params:
      model: "mistral/mistral-medium"
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: mistral-large-latest
    litellm_params:
      model: "mistral/mistral-large-latest"
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: huggingface-mistral-7b # model alias
    litellm_params: # actual params for litellm.completion()
      model: "huggingface/mistralai/Mistral-7B-Instruct-v0.2"
      api_key: "os.environ/HUGGINGFACE_API_KEY"
      # initial_prompt_value: "\n"
      # roles: {"system":{"pre_message":"<|im_start|>system\n", "post_message":"<|im_end|>"}, "assistant":{"pre_message":"<|im_start|>assistant\n","post_message":"<|im_end|>"}, "user":{"pre_message":"<|im_start|>user\n","post_message":"<|im_end|>"}}
      # final_prompt_value: "\n"
      # bos_token: "<s>"
      # eos_token: "</s>"
      max_tokens: 4096
  - model_name: gpt-3.5-turbo ### RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: gpt-3.5-turbo ### MODEL NAME sent to `litellm.completion()` ###
  # - model_name: anthropic-claude
  #   litellm_params:
  #     model: bedrock/anthropic.claude-instant-v1